### ISSUE TITLE
Support for "when" in workflow

### ISSUE THREAD

**Issue by shindex-rhems** [suzuki-shunsuke/circleci-config-merge#44]
Thanks to a fast response, top level parameters are now supported. #35 

I tried the latest version of `circleci-config-merge` and found a new problem.
The `when` phrase is not merged in the `workflow`.

I apologize for not reporting the related problem in the same issue.

```
version: 2.1

parameters: // THIS IS MERGED.
  run_integration_tests:
    type: boolean
    default: false

workflows:
  version: 2
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >> // THIS IS NOT MERGED.
    jobs:
      - mytestjob

jobs:
  mytestjob:
    steps:
      - checkout
      - ... # job steps
```
